### PR TITLE
Fix diffs with different timezones, `Date` diffs and `#in_years`

### PR DESCRIPTION
**Pull request by AlexWayfer**
Add `.ruby-version` to `.gitignore`.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
New fixes added. :grimacing:

**Comment by AlexWayfer** [comment]
OK, I'll try to fix the offense about class length.

**Comment by excpt** [comment]
> OK, I'll try to fix the offense about class length.

Please don't. This is not important.

I'll tune it down. I just need to set it up properly first.

This is just a recommendation.

**Comment by AlexWayfer** [comment]
> Please don't. This is not important.

OK, as you want (I just love myself to fit into RuboCop standards).

Now I see fails in CI for Ruby < 2.7, I need to fix them.

**Comment by AlexWayfer** [comment]
> Now I see fails in CI for Ruby < 2.7, I need to fix them.

Done, that was easy.

**Comment by AlexWayfer** [comment]
Sorry, I still see problems in my project with `moments` usage. I want to re-check all things again.

**Comment by AlexWayfer** [comment]
> Sorry, I still see problems in my project with `moments` usage. I want to re-check all things again.

No, everything is OK, there was a typo in tests of my project.

**Comment by AlexWayfer** [comment]
Thank you! I'm glad to use your project and help.

**Pull request merged**
